require 'rubygems'
require 'rake'
require 'rake/clean'


def test_suite_cmdline
  require 'find'
  files = []
  Find.find("test") do |f|
    files << f if File.basename(f) =~ /.*test.*\.rb$/
  end

  Find.find("src") do |f|
    files << f if File.basename(f) =~ /.*\.rb$/
  end

  puts "Files are #{files}"

  cmdline = "ruby -w -I.:lib:ext:test -rtest/unit -e '%w[#{files.join(' ')}].each {|f| require f}'"
end


desc "Testing library XAdES pure ruby"
task :units do
    cmdline = "#{test_suite_cmdline}"
    puts cmdline
    system cmdline
end

desc "Testing XMLdSIG library"
task :test_deps do
    puts "Running xmldsig tests"
    cmdline = "cd deps;ruby runtests.rb"
    system cmdline
end


desc "Testing library (pure ruby and extension)"
task :test => [  :test_deps, :units ]

